# Welcome to Jekyll!
#

# Site settings
title: Claudia Cerqueira
description: |
  Postdoctoral Researcher at The Brazilian Center of Analysis and Planning â€“ CEBRAP
owner: Claudia Cerqueira # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: claudiacerqn@cebrap.org.br
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://claudiacerqueira.github.io/" # the base hostname & protocol for your site
social:
  #github: https://github.com/claudiacerqn
  email: mailto:claudiacerqn@gmail.com
  twitter: http://twitter.com/claudiacerqn
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
